name = "PlutoShowHelpers"
uuid = "61f21f9a-4073-5473-9260-49250f3db370"
authors = ["Alberto Mengali <a.mengali@gmail.com>"]
version = "0.3.0"

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"

[compat]
AbstractPlutoDingetjes = "1.3.2"
ConstructionBase = "1.5.8"
HypertextLiteral = "0.9.5"
julia = "1.10"
