name = "PlutoShowHelpers"
uuid = "61f21f9a-4073-5473-9260-49250f3db370"
authors = ["Alberto Mengali <a.mengali@gmail.com>"]
version = "0.3.0-DEV"

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"

[compat]
AbstractPlutoDingetjes = "1.3.2"
HypertextLiteral = "0.9.5"
NamedTupleTools = "0.14.3"
julia = "1.10"
